FROM node:lts-slim

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install --no-install-recommends --yes curl ca-certificates ttfautohint
COPY build.sh /usr/bin/build-iosevka.sh

WORKDIR /work
ENTRYPOINT /usr/bin/build-iosevka.sh
