(setq package-selected-packages '(bazel
                                  clang-format
                                  consult
                                  counsel
                                  diminish
                                  dockerfile-mode
                                  eglot
                                  flycheck
                                  go-mode
                                  google-c-style
                                  ivy
                                  json-mode
                                  magit
                                  marginalia
                                  markdown-mode
                                  protobuf-mode
                                  swiper
                                  tuareg
                                  vertico
                                  yaml-mode))
